# Generated by Django 2.2.5 on 2021-05-01 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Коллекция Паролей',
                'verbose_name_plural': 'Коллекций Паролей',
            },
        ),
        migrations.CreateModel(
            name='WifiPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('wifi_name', models.CharField(max_length=100, verbose_name='Логин')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager.PasswordCollection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Пароль от вайфай',
                'verbose_name_plural': 'Пароли от вайфай',
            },
        ),
        migrations.CreateModel(
            name='WebSitePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('website', models.CharField(max_length=255, verbose_name='Веб сайт')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager.PasswordCollection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Пароль от вебсайта',
                'verbose_name_plural': 'Пароли от вебсайта',
            },
        ),
    ]
