# Generated by Django 2.2.5 on 2021-05-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0004_auto_20210506_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitebookmark',
            name='website_password',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='password_manager.WebSitePassword'),
        ),
    ]
