# Generated by Django 2.2.5 on 2021-05-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0005_auto_20210506_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitebookmark',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='password_manager.PasswordCollection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='websitepassword',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='password_manager.PasswordCollection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='wifipassword',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='password_manager.PasswordCollection', verbose_name='Коллекция'),
        ),
    ]
