# Generated by Django 2.2.5 on 2021-05-07 09:49

from django.db import migrations, models
import password_manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0006_auto_20210506_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitebookmark',
            name='password',
            field=models.CharField(max_length=100, validators=[password_manager.validators.validate_password], verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='websitebookmark',
            name='url',
            field=models.CharField(max_length=255, validators=[password_manager.validators.validate_url], verbose_name='Ссылка на закладку'),
        ),
        migrations.AlterField(
            model_name='websitepassword',
            name='login',
            field=models.CharField(max_length=100, validators=[password_manager.validators.validate_login], verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='websitepassword',
            name='password',
            field=models.CharField(max_length=100, validators=[password_manager.validators.validate_password], verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='wifipassword',
            name='password',
            field=models.CharField(max_length=100, validators=[password_manager.validators.validate_password], verbose_name='Пароль'),
        ),
    ]
