# Generated by Django 2.2.5 on 2021-05-04 13:58

import auth_.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mainuser',
            managers=[
                ('objects', auth_.models.MainUserManager()),
            ],
        ),
    ]
