# Generated by Django 2.2.5 on 2021-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0005_auto_20210507_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
